// Bilingual strings. PT-PT primary, EN secondary.
window.STRINGS = {
  pt: {
    cart: 'Cesto',
    caseOf6: 'Caixa · 6 garrafas',
    perBottle: '/ garrafa',
    addCase: 'Adicionar caixa',
    outOfStock: 'Esgotado',
    inStock: 'Em stock',
    vintage: 'Colheita',
    backToShop: '← Voltar à loja',
    checkout: 'Finalizar Encomenda',
    billing: 'Dados de Faturação',
    delivery: 'Morada de Entrega',
    sameAsBilling: 'Igual aos dados de faturação',
    name: 'Nome',
    surname: 'Apelido',
    email: 'E-mail',
    phone: 'Telefone',
    nif: 'NIF (opcional)',
    address: 'Morada',
    postcode: 'Código Postal',
    city: 'Localidade',
    country: 'País',
    countryDefault: 'Portugal',
    summary: 'Resumo da Encomenda',
    subtotal: 'Subtotal',
    taxIncl: 'IVA incluído',
    total: 'Total',
    placeOrder: 'Confirmar Encomenda',
    contactNote: 'Após a confirmação, entraremos em contacto por e-mail para acertar pagamento e entrega.',
    emptyCart: 'O cesto está vazio.',
    // age gate
    ageBrandSub: 'Douro Superior · Portugal',
    ageQuestion: ['Tem idade legal', 'para o consumo de ', 'álcool', '?'],
    ageYes: 'Sim, sou maior de 18',
    ageNo: 'Não',
    ageFine: 'Ao entrar, confirma que tem a idade legal para o consumo de bebidas alcoólicas no seu país de residência. Beba com moderação.',
    ageDeniedTitle: ['Lamentamos.', 'Volte quando tiver ', 'idade legal', '.'],
    ageDeniedFine: 'Saúde.',
  },
  en: {
    cart: 'Cart',
    caseOf6: 'Case · 6 bottles',
    perBottle: '/ bottle',
    addCase: 'Add case',
    outOfStock: 'Sold out',
    inStock: 'In stock',
    vintage: 'Vintage',
    backToShop: '← Back to shop',
    checkout: 'Checkout',
    billing: 'Billing Details',
    delivery: 'Delivery Address',
    sameAsBilling: 'Same as billing details',
    name: 'First name',
    surname: 'Last name',
    email: 'Email',
    phone: 'Phone',
    nif: 'Tax ID (optional)',
    address: 'Address',
    postcode: 'Postcode',
    city: 'City',
    country: 'Country',
    countryDefault: 'Portugal',
    summary: 'Order Summary',
    subtotal: 'Subtotal',
    taxIncl: 'VAT included',
    total: 'Total',
    placeOrder: 'Place Order',
    contactNote: 'After confirmation, we will contact you by email to arrange payment and delivery.',
    emptyCart: 'Your cart is empty.',
    ageBrandSub: 'Douro Superior · Portugal',
    ageQuestion: ['Are you of legal', 'age to consume ', 'alcohol', '?'],
    ageYes: 'Yes, I am 18 or older',
    ageNo: 'No',
    ageFine: 'By entering, you confirm that you are of legal drinking age in your country of residence. Please drink responsibly.',
    ageDeniedTitle: ['Sorry.', 'Come back when you are of ', 'legal age', '.'],
    ageDeniedFine: 'Cheers.',
  },
};

window.WINE_COPY = {
  pt: {
    branco: { varietal: 'Vinhas Velhas · Branco' },
    rose: { varietal: 'Rosé' },
    quinta: { varietal: 'Tinto · Edição limitada' },
    tinto: { varietal: 'Tinto · Reserva' },
  },
  en: {
    branco: { varietal: 'Old Vines · White' },
    rose: { varietal: 'Rosé' },
    quinta: { varietal: 'Red · Limited Edition' },
    tinto: { varietal: 'Red · Reserva' },
  },
};
