// Bilingual strings. PT-PT primary, EN secondary.
window.STRINGS = {
  pt: {
    cart: 'Cesto',
    caseOf6: 'Caixa · 6 garrafas',
    perBottle: '/ garrafa',
    addCase: 'Adicionar caixa',
    addedToCart: 'Adicionado ✓',
    remove: 'Remover',
    outOfStock: 'Esgotado',
    inStock: 'Em stock',
    vintage: 'Colheita',
    backToShop: '← Voltar à loja',
    checkout: 'Finalizar Encomenda',
    billing: 'Dados de Faturação',
    delivery: 'Morada de Entrega',
    sameAsBilling: 'Igual aos dados de faturação',
    name: 'Nome',
    surname: 'Apelido',
    email: 'E-mail',
    phone: 'Telefone',
    nif: 'NIF (opcional)',
    address: 'Morada',
    postcode: 'Código Postal',
    city: 'Localidade',
    country: 'País',
    countryDefault: 'Portugal',
    summary: 'Resumo da Encomenda',
    yourOrder: 'A sua encomenda',
    cases: 'caixas',
    case_one: 'caixa',
    bottles: 'garrafas',
    perBottleAbbrev: '/ garrafa',
    perCaseAbbrev: '/ caixa',
    subtotal: 'Subtotal',
    discount: 'Desconto LDW (−30%)',
    taxIncl: 'IVA incluído',
    total: 'Total',
    placeOrder: 'Confirmar Encomenda',
    payNow: 'Pagar agora →',
    checkoutNote: 'Os dados de faturação, NIF e morada de entrega são preenchidos no passo seguinte, na página segura do Stripe.',
    freeShipping: 'Envio grátis · Portugal Continental',
    secureNote: 'Pagamento seguro processado por Stripe. Os dados de entrega e faturação são recolhidos no passo seguinte.',
    contactNote: 'Pagamento por MBWay, cartão ou Multibanco. Receberá um e-mail com a confirmação.',
    emptyCart: 'O cesto está vazio.',
    emptyCartCta: 'Voltar à loja',
    emptyCartLead: 'Ainda não adicionou nenhuma caixa de vinho.',
    // age gate
    ageBrandSub: 'Douro Superior · Portugal',
    ageQuestion: ['Tem idade legal', 'para o consumo de ', 'álcool', '?'],
    ageYes: 'Sim, sou maior de 18',
    ageNo: 'Não',
    ageFine: 'Ao entrar, confirma que tem a idade legal para o consumo de bebidas alcoólicas no seu país de residência. Beba com moderação.',
    ageDeniedTitle: ['Lamentamos.', 'Volte quando tiver ', 'idade legal', '.'],
    ageDeniedFine: 'Saúde.',
  },
  en: {
    cart: 'Cart',
    caseOf6: 'Case · 6 bottles',
    perBottle: '/ bottle',
    addCase: 'Add case',
    addedToCart: 'Added ✓',
    remove: 'Remove',
    outOfStock: 'Sold out',
    inStock: 'In stock',
    vintage: 'Vintage',
    backToShop: '← Back to shop',
    checkout: 'Checkout',
    billing: 'Billing Details',
    delivery: 'Delivery Address',
    sameAsBilling: 'Same as billing details',
    name: 'First name',
    surname: 'Last name',
    email: 'Email',
    phone: 'Phone',
    nif: 'Tax ID (optional)',
    address: 'Address',
    postcode: 'Postcode',
    city: 'City',
    country: 'Country',
    countryDefault: 'Portugal',
    summary: 'Order Summary',
    yourOrder: 'Your order',
    cases: 'cases',
    case_one: 'case',
    bottles: 'bottles',
    perBottleAbbrev: '/ bottle',
    perCaseAbbrev: '/ case',
    subtotal: 'Subtotal',
    discount: 'LDW discount (−30%)',
    taxIncl: 'VAT included',
    total: 'Total',
    placeOrder: 'Place Order',
    payNow: 'Pay now →',
    checkoutNote: 'Billing, tax ID and shipping details are filled in the next step, on Stripe\'s secure page.',
    freeShipping: 'Free shipping · Mainland Portugal',
    secureNote: 'Secure payment processed by Stripe. Shipping and billing details are collected in the next step.',
    contactNote: 'Pay by MBWay, card or Multibanco. You will receive an email confirmation.',
    emptyCart: 'Your cart is empty.',
    emptyCartCta: 'Back to shop',
    emptyCartLead: 'You haven\'t added any cases yet.',
    ageBrandSub: 'Douro Superior · Portugal',
    ageQuestion: ['Are you of legal', 'age to consume ', 'alcohol', '?'],
    ageYes: 'Yes, I am 18 or older',
    ageNo: 'No',
    ageFine: 'By entering, you confirm that you are of legal drinking age in your country of residence. Please drink responsibly.',
    ageDeniedTitle: ['Sorry.', 'Come back when you are of ', 'legal age', '.'],
    ageDeniedFine: 'Cheers.',
  },
};

window.WINE_COPY = {
  pt: {
    branco: { varietal: 'Branco' },
    rose: { varietal: 'Rosé' },
    quinta: { varietal: 'Tinto' },
    tinto: { varietal: 'Tinto' },
  },
  en: {
    branco: { varietal: 'White' },
    rose: { varietal: 'Rosé' },
    quinta: { varietal: 'Red' },
    tinto: { varietal: 'Red' },
  },
};
